/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DraftsRouteImport } from './routes/drafts'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAchievementsRouteImport } from './routes/admin/achievements'
import { Route as AdminCommentsRouteImport } from './routes/admin/comments'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminTagsRouteImport } from './routes/admin/tags'
import { Route as AdminTemplatesRouteImport } from './routes/admin/templates'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminWorksRouteImport } from './routes/admin/works'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as ChatIdRouteImport } from './routes/chat/$id'
import { Route as TagsIndexRouteImport } from './routes/tags/index'
import { Route as TagsSlugRouteImport } from './routes/tags/$slug'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as TemplatesNewRouteImport } from './routes/templates/new'
import { Route as TemplatesIdIndexRouteImport } from './routes/templates/$id/index'
import { Route as UserIdIndexRouteImport } from './routes/user/$id/index'
import { Route as WorkIdIndexRouteImport } from './routes/work/$id/index'
import { Route as WorkIdEditRouteImport } from './routes/work/$id/edit'
import { Route as WorkNewEditRouteImport } from './routes/work/new/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsRoute = DraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAchievementsRoute = AdminAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorksRoute = AdminWorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => AdminRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChatRoute,
} as any)
const TagsIndexRoute = TagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsSlugRoute = TagsSlugRouteImport.update({
  id: '/tags/$slug',
  path: '/tags/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesNewRoute = TemplatesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesIdIndexRoute = TemplatesIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => TemplatesRoute,
} as any)
const UserIdIndexRoute = UserIdIndexRouteImport.update({
  id: '/user/$id/',
  path: '/user/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIdIndexRoute = WorkIdIndexRouteImport.update({
  id: '/work/$id/',
  path: '/work/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIdEditRoute = WorkIdEditRouteImport.update({
  id: '/work/$id/edit',
  path: '/work/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkNewEditRoute = WorkNewEditRouteImport.update({
  id: '/work/new/edit',
  path: '/work/new/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/drafts': typeof DraftsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/messages': typeof MessagesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/works': typeof AdminWorksRoute
  '/chat/$id': typeof ChatIdRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/templates/new': typeof TemplatesNewRoute
  '/admin/': typeof AdminIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/work/$id/edit': typeof WorkIdEditRoute
  '/work/new/edit': typeof WorkNewEditRoute
  '/templates/$id/': typeof TemplatesIdIndexRoute
  '/user/$id/': typeof UserIdIndexRoute
  '/work/$id/': typeof WorkIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/drafts': typeof DraftsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/messages': typeof MessagesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/works': typeof AdminWorksRoute
  '/chat/$id': typeof ChatIdRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/templates/new': typeof TemplatesNewRoute
  '/admin': typeof AdminIndexRoute
  '/chat': typeof ChatIndexRoute
  '/tags': typeof TagsIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/work/$id/edit': typeof WorkIdEditRoute
  '/work/new/edit': typeof WorkNewEditRoute
  '/templates/$id': typeof TemplatesIdIndexRoute
  '/user/$id': typeof UserIdIndexRoute
  '/work/$id': typeof WorkIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/drafts': typeof DraftsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/messages': typeof MessagesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/works': typeof AdminWorksRoute
  '/chat/$id': typeof ChatIdRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/templates/new': typeof TemplatesNewRoute
  '/admin/': typeof AdminIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/work/$id/edit': typeof WorkIdEditRoute
  '/work/new/edit': typeof WorkNewEditRoute
  '/templates/$id/': typeof TemplatesIdIndexRoute
  '/user/$id/': typeof UserIdIndexRoute
  '/work/$id/': typeof WorkIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/discover'
    | '/drafts'
    | '/leaderboard'
    | '/messages'
    | '/reset-password'
    | '/settings'
    | '/templates'
    | '/admin/achievements'
    | '/admin/comments'
    | '/admin/messages'
    | '/admin/reports'
    | '/admin/tags'
    | '/admin/templates'
    | '/admin/users'
    | '/admin/works'
    | '/chat/$id'
    | '/tags/$slug'
    | '/templates/new'
    | '/admin/'
    | '/chat/'
    | '/tags/'
    | '/templates/'
    | '/work/$id/edit'
    | '/work/new/edit'
    | '/templates/$id/'
    | '/user/$id/'
    | '/work/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/discover'
    | '/drafts'
    | '/leaderboard'
    | '/messages'
    | '/reset-password'
    | '/settings'
    | '/admin/achievements'
    | '/admin/comments'
    | '/admin/messages'
    | '/admin/reports'
    | '/admin/tags'
    | '/admin/templates'
    | '/admin/users'
    | '/admin/works'
    | '/chat/$id'
    | '/tags/$slug'
    | '/templates/new'
    | '/admin'
    | '/chat'
    | '/tags'
    | '/templates'
    | '/work/$id/edit'
    | '/work/new/edit'
    | '/templates/$id'
    | '/user/$id'
    | '/work/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/discover'
    | '/drafts'
    | '/leaderboard'
    | '/messages'
    | '/reset-password'
    | '/settings'
    | '/templates'
    | '/admin/achievements'
    | '/admin/comments'
    | '/admin/messages'
    | '/admin/reports'
    | '/admin/tags'
    | '/admin/templates'
    | '/admin/users'
    | '/admin/works'
    | '/chat/$id'
    | '/tags/$slug'
    | '/templates/new'
    | '/admin/'
    | '/chat/'
    | '/tags/'
    | '/templates/'
    | '/work/$id/edit'
    | '/work/new/edit'
    | '/templates/$id/'
    | '/user/$id/'
    | '/work/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  DraftsRoute: typeof DraftsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MessagesRoute: typeof MessagesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
  TagsSlugRoute: typeof TagsSlugRoute
  TagsIndexRoute: typeof TagsIndexRoute
  WorkIdEditRoute: typeof WorkIdEditRoute
  WorkNewEditRoute: typeof WorkNewEditRoute
  UserIdIndexRoute: typeof UserIdIndexRoute
  WorkIdIndexRoute: typeof WorkIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts': {
      id: '/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof DraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/achievements': {
      id: '/admin/achievements'
      path: '/achievements'
      fullPath: '/admin/achievements'
      preLoaderRoute: typeof AdminAchievementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/works': {
      id: '/admin/works'
      path: '/works'
      fullPath: '/admin/works'
      preLoaderRoute: typeof AdminWorksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/tags/': {
      id: '/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof TagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$slug': {
      id: '/tags/$slug'
      path: '/tags/$slug'
      fullPath: '/tags/$slug'
      preLoaderRoute: typeof TagsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/new': {
      id: '/templates/new'
      path: '/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof TemplatesNewRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/$id/': {
      id: '/templates/$id/'
      path: '/$id'
      fullPath: '/templates/$id/'
      preLoaderRoute: typeof TemplatesIdIndexRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/user/$id/': {
      id: '/user/$id/'
      path: '/user/$id'
      fullPath: '/user/$id/'
      preLoaderRoute: typeof UserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$id/': {
      id: '/work/$id/'
      path: '/work/$id'
      fullPath: '/work/$id/'
      preLoaderRoute: typeof WorkIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$id/edit': {
      id: '/work/$id/edit'
      path: '/work/$id/edit'
      fullPath: '/work/$id/edit'
      preLoaderRoute: typeof WorkIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/new/edit': {
      id: '/work/new/edit'
      path: '/work/new/edit'
      fullPath: '/work/new/edit'
      preLoaderRoute: typeof WorkNewEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAchievementsRoute: typeof AdminAchievementsRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWorksRoute: typeof AdminWorksRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAchievementsRoute: AdminAchievementsRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminTagsRoute: AdminTagsRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWorksRoute: AdminWorksRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ChatRouteChildren {
  ChatIdRoute: typeof ChatIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIdRoute: ChatIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface TemplatesRouteChildren {
  TemplatesNewRoute: typeof TemplatesNewRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  TemplatesIdIndexRoute: typeof TemplatesIdIndexRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesNewRoute: TemplatesNewRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  TemplatesIdIndexRoute: TemplatesIdIndexRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  DraftsRoute: DraftsRoute,
  LeaderboardRoute: LeaderboardRoute,
  MessagesRoute: MessagesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
  TagsSlugRoute: TagsSlugRoute,
  TagsIndexRoute: TagsIndexRoute,
  WorkIdEditRoute: WorkIdEditRoute,
  WorkNewEditRoute: WorkNewEditRoute,
  UserIdIndexRoute: UserIdIndexRoute,
  WorkIdIndexRoute: WorkIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
