/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DraftsRouteImport } from './routes/drafts'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as MessagesIdRouteImport } from './routes/messages/$id'
import { Route as TagsIndexRouteImport } from './routes/tags/index'
import { Route as TagsSlugRouteImport } from './routes/tags/$slug'
import { Route as UserIdIndexRouteImport } from './routes/user/$id/index'
import { Route as WorkIdIndexRouteImport } from './routes/work/$id/index'
import { Route as WorkIdEditRouteImport } from './routes/work/$id/edit'
import { Route as WorkNewEditRouteImport } from './routes/work/new/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsRoute = DraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MessagesRoute,
} as any)
const TagsIndexRoute = TagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsSlugRoute = TagsSlugRouteImport.update({
  id: '/tags/$slug',
  path: '/tags/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdIndexRoute = UserIdIndexRouteImport.update({
  id: '/user/$id/',
  path: '/user/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIdIndexRoute = WorkIdIndexRouteImport.update({
  id: '/work/$id/',
  path: '/work/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIdEditRoute = WorkIdEditRouteImport.update({
  id: '/work/$id/edit',
  path: '/work/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkNewEditRoute = WorkNewEditRouteImport.update({
  id: '/work/new/edit',
  path: '/work/new/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/drafts': typeof DraftsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/messages': typeof MessagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/messages/$id': typeof MessagesIdRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/tags/': typeof TagsIndexRoute
  '/work/$id/edit': typeof WorkIdEditRoute
  '/work/new/edit': typeof WorkNewEditRoute
  '/user/$id/': typeof UserIdIndexRoute
  '/work/$id/': typeof WorkIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/drafts': typeof DraftsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/messages': typeof MessagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/messages/$id': typeof MessagesIdRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/tags': typeof TagsIndexRoute
  '/work/$id/edit': typeof WorkIdEditRoute
  '/work/new/edit': typeof WorkNewEditRoute
  '/user/$id': typeof UserIdIndexRoute
  '/work/$id': typeof WorkIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/drafts': typeof DraftsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/messages': typeof MessagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/messages/$id': typeof MessagesIdRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/tags/': typeof TagsIndexRoute
  '/work/$id/edit': typeof WorkIdEditRoute
  '/work/new/edit': typeof WorkNewEditRoute
  '/user/$id/': typeof UserIdIndexRoute
  '/work/$id/': typeof WorkIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/discover'
    | '/drafts'
    | '/leaderboard'
    | '/messages'
    | '/reset-password'
    | '/settings'
    | '/templates'
    | '/messages/$id'
    | '/tags/$slug'
    | '/tags/'
    | '/work/$id/edit'
    | '/work/new/edit'
    | '/user/$id/'
    | '/work/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/discover'
    | '/drafts'
    | '/leaderboard'
    | '/messages'
    | '/reset-password'
    | '/settings'
    | '/templates'
    | '/messages/$id'
    | '/tags/$slug'
    | '/tags'
    | '/work/$id/edit'
    | '/work/new/edit'
    | '/user/$id'
    | '/work/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/discover'
    | '/drafts'
    | '/leaderboard'
    | '/messages'
    | '/reset-password'
    | '/settings'
    | '/templates'
    | '/messages/$id'
    | '/tags/$slug'
    | '/tags/'
    | '/work/$id/edit'
    | '/work/new/edit'
    | '/user/$id/'
    | '/work/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  DiscoverRoute: typeof DiscoverRoute
  DraftsRoute: typeof DraftsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  TagsSlugRoute: typeof TagsSlugRoute
  TagsIndexRoute: typeof TagsIndexRoute
  WorkIdEditRoute: typeof WorkIdEditRoute
  WorkNewEditRoute: typeof WorkNewEditRoute
  UserIdIndexRoute: typeof UserIdIndexRoute
  WorkIdIndexRoute: typeof WorkIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts': {
      id: '/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof DraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$id': {
      id: '/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof MessagesIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/tags/': {
      id: '/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof TagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$slug': {
      id: '/tags/$slug'
      path: '/tags/$slug'
      fullPath: '/tags/$slug'
      preLoaderRoute: typeof TagsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/': {
      id: '/user/$id/'
      path: '/user/$id'
      fullPath: '/user/$id/'
      preLoaderRoute: typeof UserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$id/': {
      id: '/work/$id/'
      path: '/work/$id'
      fullPath: '/work/$id/'
      preLoaderRoute: typeof WorkIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$id/edit': {
      id: '/work/$id/edit'
      path: '/work/$id/edit'
      fullPath: '/work/$id/edit'
      preLoaderRoute: typeof WorkIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/new/edit': {
      id: '/work/new/edit'
      path: '/work/new/edit'
      fullPath: '/work/new/edit'
      preLoaderRoute: typeof WorkNewEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MessagesRouteChildren {
  MessagesIdRoute: typeof MessagesIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesIdRoute: MessagesIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  DiscoverRoute: DiscoverRoute,
  DraftsRoute: DraftsRoute,
  LeaderboardRoute: LeaderboardRoute,
  MessagesRoute: MessagesRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  TagsSlugRoute: TagsSlugRoute,
  TagsIndexRoute: TagsIndexRoute,
  WorkIdEditRoute: WorkIdEditRoute,
  WorkNewEditRoute: WorkNewEditRoute,
  UserIdIndexRoute: UserIdIndexRoute,
  WorkIdIndexRoute: WorkIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
