export const ACHIEVEMENT_SEEDS = [
    {
        key: "first_publish",
        name: "初次发布",
        description: "发布你的第一个作品",
        icon: "Rocket",
        category: "publish",
        threshold: 1,
    },
    {
        key: "publish_5",
        name: "创作达人",
        description: "累计发布 5 个作品",
        icon: "PenTool",
        category: "publish",
        threshold: 5,
    },
    {
        key: "publish_20",
        name: "创作大师",
        description: "累计发布 20 个作品",
        icon: "Crown",
        category: "publish",
        threshold: 20,
    },
    {
        key: "spark_first",
        name: "第一次心动",
        description: "收到第一个火花",
        icon: "Sparkles",
        category: "social",
        threshold: 1,
    },
    {
        key: "spark_10",
        name: "人气新星",
        description: "累计收到 10 个火花",
        icon: "Star",
        category: "social",
        threshold: 10,
    },
    {
        key: "spark_100",
        name: "社区之星",
        description: "累计收到 100 个火花",
        icon: "Sun",
        category: "social",
        threshold: 100,
    },
    {
        key: "remix_first",
        name: "灵感碰撞",
        description: "复刻一个作品",
        icon: "GitFork",
        category: "social",
        threshold: 1,
    },
    {
        key: "remix_10",
        name: "复刻达人",
        description: "累计复刻 10 个作品",
        icon: "Repeat",
        category: "social",
        threshold: 10,
    },
    {
        key: "follow_first",
        name: "社交入门",
        description: "关注第一个用户",
        icon: "UserPlus",
        category: "social",
        threshold: 1,
    },
    {
        key: "follower_10",
        name: "小有名气",
        description: "拥有 10 个粉丝",
        icon: "Users",
        category: "social",
        threshold: 10,
    },
    {
        key: "follower_100",
        name: "社区领袖",
        description: "拥有 100 个粉丝",
        icon: "Award",
        category: "social",
        threshold: 100,
    },
    {
        key: "give_spark_10",
        name: "热情观众",
        description: "累计给出 10 个火花",
        icon: "Heart",
        category: "explore",
        threshold: 10,
    },
    {
        key: "give_spark_100",
        name: "超级粉丝",
        description: "累计给出 100 个火花",
        icon: "Flame",
        category: "explore",
        threshold: 100,
    },
];
